In [2]:
from hubbard.solver import ED_solver
import numpy as np

solver = ED_solver(
    n_int=2, # interacting sites
    n_noint=0, # no-interacting sites (bath), 0 if not impurity system
    n_particle=[(1,1)], # one-up and one-down
    nspin=1, # 1: spin-degenerate, 2: spin collinear, 4: spin noncollinear
)

In [3]:
solver.solve(
    T=np.kron(np.array([ # single particle part
        [-1,0.5],
        [0.5,-1]
    ]), np.eye(2)),
    intparam={"U":3.0,"Up":3.0,"J":0.0, "Jp":0.0} # interacting part
)

True

In [4]:
print(solver.cal_RDM(solver.vec))

[[ 0.5  0.  -0.5  0. ]
 [ 0.   0.5  0.  -0.5]
 [-0.5  0.   0.5  0. ]
 [ 0.  -0.5  0.   0.5]]


In [5]:
h1e, g2e = solver.get_Hqc(True)
print(h1e)
print(g2e)

[[-1.   0.5  0.   0. ]
 [ 0.5 -1.   0.   0. ]
 [ 0.   0.  -1.   0.5]
 [ 0.   0.   0.5 -1. ]]
[[[[0. 0. 0. 0.]
   [0. 3. 0. 0.]
   [0. 0. 3. 0.]
   [0. 0. 0. 3.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[3. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 3. 0.]
   [0. 0. 0. 3.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[3. 0. 0. 0.]
   [0. 3. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 3.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 

In [6]:
solver.solve(
    T=h1e,
    intparam={"g2e":g2e, "int_type":"QC"} # Quamtum chemistry type of Hamiltonian definition
)

True

In [7]:
solver.cal_RDM(solver.vec)

array([[ 0.5,  0. , -0.5,  0. ],
       [ 0. ,  0.5,  0. , -0.5],
       [-0.5,  0. ,  0.5,  0. ],
       [ 0. , -0.5,  0. ,  0.5]])